include: package:flutter_lints/flutter.yaml

linter:
  rules:
    - avoid_print
    - prefer_single_quotes
    - prefer_relative_imports
    - require_trailing_commas
    - use_super_parameters
    - discarded_futures
    - unrelated_type_equality_checks
    - use_enums
    - use_named_constants
    - avoid_returning_null_for_void
    - only_throw_errors
    - sized_box_for_whitespace
    - sized_box_shrink_expand