name: Pre Merge

on:
  pull_request:
    branches: [ main, develop ]

jobs:
  pre-merge:
    runs-on: macos-latest

    steps:
      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Merge ${{ github.head_ref}} into ${{ github.base_ref }} branch
        run: git merge origin/${{ github.base_ref }}

      - name: Cache Flutter Dependencies
        uses: actions/cache@v1
        with:
          path: /Users/runner/hostedtoolcache/flutter
          key: ${{ runner.os }}-flutter

      - name: Run Flutter Pub Get
        run: flutter pub get

      - name: Flutter Format
        run: dart format --set-exit-if-changed .

      - name: Flutter Analyze
        run: dart analyze --fatal-infos

      - name: Run Unit Test
        run: flutter test
